### ISSUE TITLE
progress tracking for reworked wayland client

### ISSUE THREAD

**Issue by cyuria** [cyuria/watlas#2]
- [x] Use `xdg_shell` to create a window
- [x] Implement frame callbacks
- [ ] Implement window surface damaging
- [ ] Allow customisation of window resizing
- [ ] Enable `wlr_layer_shell`
- [ ] Implement correct window resource destruction/deallocation
- [ ] Add event handling and an event loop with `wl_seat`
- [ ] Multiple frame buffers and correct `wl_buffer` resource handling to prevent tearing and race conditions
- [ ] Logging/returning frame times
